"""Build labels/unified-full.yaml: one label map over every TAXONOMY corpus in data/.

Measure before classifying (the standing rule): each split corpus in data/ is scored on its
label health, and only taxonomies may VOTE on spellings. A corpus is excluded from voting if
its labels are placeholders (> 5% `e_N`), mostly singletons (> 40%), or an open vocabulary
(> 10,000 distinct labels) -- measured 2026-09-30, the populations separate cleanly: taxonomy
corpora sit at <= 29% singletons, the rest at >= 43% or carry placeholders. Singleton share
alone is NOT enough: NuNER reads 0.2% singletons by this counter with 242,711 labels.

Roles, passed to `build_label_maps.build`:

* voters     -- taxonomy corpora; they form clusters and pick winners;
* canonical  -- eb17-best's taxonomy corpora; the base's spellings win (standing rule);
* followers  -- excluded but TRAINED corpora; a spelling folding onto a voter label maps to it,
               and a cluster found only among followers collapses to its majority spelling
               (fold-only, so it cannot merge two concepts);
* zero-shot  -- Pile-NER, NuNER and their replay; left out entirely, kept raw by configs
               through `data.labels_passthrough`.

    uv run python tools/train/build_unified_full.py
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_label_maps as B  # noqa: E402

ZERO_SHOT = {"pile_ner_def", "nuner_full", "replay_pile30"}
PLACEHOLDER = re.compile(r"^e_\d+$")
BASE_CONFIG = "tools/train/config/base/eb17-best.yaml"
OUT = Path("tools/train/config/labels/unified-full.yaml")


def split_files(name):
    return [f"data/{name}.{s}.jsonl" for s in ("train", "val", "test")
            if Path(f"data/{name}.{s}.jsonl").exists()]


def health(name):
    """(distinct labels, placeholder share of uses, singleton share of labels)."""
    uses = Counter()
    for f in split_files(name):
        with open(f, encoding="utf-8") as fh:
            for line in fh:
                if line.strip():
                    uses.update(lab for _, lab in B.labels_by_category(json.loads(line)))
    if not uses:
        return None
    ph = sum(n for lab, n in uses.items() if PLACEHOLDER.match(lab)) / sum(uses.values())
    return len(uses), ph, sum(1 for n in uses.values() if n == 1) / len(uses)


def classify():
    """Return (voters, excluded {name: reasons}) over every split corpus in data/."""
    names = sorted({p.name.split(".")[0] for p in Path("data").glob("*.train.jsonl")})
    voters, excluded = [], {}
    for name in names:
        h = health(name)
        if h is None:
            continue
        n, ph, sg = h
        reasons = [r for r, hit in (("zero-shot", name in ZERO_SHOT), (f"placeholder {ph:.0%}", ph > 0.05),
                                    (f"singletons {sg:.0%}", sg > 0.40), (f"{n:,} labels", n > 10000)) if hit]
        (excluded.__setitem__(name, reasons) if reasons else voters.append(name))
    return voters, excluded


def main():
    voters, excluded = classify()
    base = {f.split("/")[-1].split(".")[0] for f in B.config_files(BASE_CONFIG)}
    canonical = sorted(base & set(voters))
    followers = sorted(set(excluded) - ZERO_SHOT)
    files = lambda names: [f for n in names for f in split_files(n)]
    maps, _ = B.build(files(voters), files(canonical), files(followers))
    print(f"voters {len(voters)} | canonical {len(canonical)} | followers {len(followers)} | "
          f"excluded {len(excluded)}")
    for name, reasons in sorted(excluded.items()):
        print(f"  excluded {name}: {', '.join(reasons)}")
    for c, m in maps.items():
        print(f"  {c}: {len(m)} spellings collapse")
    header = ("# Unified label space, FULL -- GENERATED by tools/train/build_unified_full.py.\n"
              f"# voters = {len(voters)} TAXONOMY corpora of data/; canonical = eb17-best's taxonomy\n"
              "# corpora (the base's spellings win); followers = trained non-taxonomy corpora, mapped\n"
              "# onto a voter spelling of the same fold, and their own fold-only clusters collapsed.\n"
              "# Zero-shot corpora (pile_ner_def, nuner_full, replay_pile30) are not mapped: configs\n"
              "# keep them raw with data.labels_passthrough. Supersedes labels/unified.yaml (built\n"
              "# 2026-09-02 from 19 corpora) for NEW lines; the configs on unified.yaml are untouched.\n")
    block = {"labels": {c: {"rollup": False, "separator": ".", "map": m} for c, m in maps.items()}}
    OUT.write_text(header + yaml.safe_dump(block, allow_unicode=True, sort_keys=False,
                                           default_flow_style=False), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
