"""Generate the three NaN/runtime probe configs from the real 10K joint config.

Derived rather than hand-copied so the probes cannot drift from the config whose
failure we are diagnosing. Each probe changes exactly ONE thing from probe A:

    A  sdpa + bf16   baseline -- reproduce the NaN on a single GPU (no DDP)
    B  sdpa + fp32   isolates DTYPE (never actually tested: CPU autocast bf16 is
                     a no-op for ModernBERT, so the earlier "0/125 on CPU" run
                     compared fp32 against fp32)
    C  FA2  + bf16   fix candidate AND the runtime measurement -- mmBERT is built
                     for FlashAttention 2 + unpadding (arXiv 2509.06888 Table 8);
                     sdpa pays full L x L attention on 2/3 layers that only need
                     a +/-64 band.

Single GPU throughout, so DDP is out of the matrix. If A does not reproduce, DDP
is the remaining suspect and the next multi-GPU launch is re-rolling the dice.

Run from the repo root::

    uv run python tools/train/make_nan_probe_configs.py
"""
import copy
from pathlib import Path

import yaml

SRC = Path("tools/train/config/joint-boundary-mmbert-10k.yaml")
OUT = Path("tools/train/config")

# Enough optimizer steps to hit the NaN with near certainty at the observed ~58%
# per-micro-batch rate, and enough logged steps to time a stable s/it.
MAX_STEPS = 60

PROBES = {
    "a": ("sdpa + bf16 (baseline)", {}, {"bf16": True, "fp16": False}),
    "b": ("sdpa + fp32 (isolates dtype)", {}, {"bf16": False, "fp16": False}),
    "c": ("flash_attention_2 + bf16", {"attn_implementation": "flash_attention_2"},
          {"bf16": True, "fp16": False}),
}


def main() -> None:
    base = yaml.safe_load(SRC.read_text(encoding="utf-8"))
    for tag, (label, model_over, train_over) in PROBES.items():
        cfg = copy.deepcopy(base)
        cfg["model"].update(model_over)
        cfg["training"].update(train_over)
        cfg["training"].update({
            "output_dir": f"./out/probe-nan-{tag}",
            "experiment_name": f"probe_nan_{tag}",
            "data_parallel": False,
            "max_steps": MAX_STEPS,
            # Probes measure the training step only: no eval, no checkpoints.
            "eval_strategy": "no",
            "save_best": False,
            "logging_steps": 5,
        })
        dst = OUT / f"probe-nan-{tag}.yaml"
        dst.write_text(
            f"# PROBE {tag.upper()}: {label}\n"
            f"# Generated by tools/train/make_nan_probe_configs.py -- do not edit by hand.\n"
            + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
        print(f"{dst}  ({label})")


if __name__ == "__main__":
    main()
