"""Write a fine-tuning `labels_file`: the base checkpoint's label map plus a new corpus.

`build_label_maps.py --canonical` makes a base win by SCANNING the base's training corpora,
which are absent off the training machine and unpublished for fastino. The checkpoint itself
carries the base's spellings (`label_map`, `default_schema`), so this builds from that:

  1. start from the base's own `label_map` (replayed exactly as the base trained);
  2. add the corpus's own spelling clusters (`build_label_maps.build`: case/punctuation
     folds plus the hand-pinned SYNONYMS) -- and where a cluster holds a spelling the BASE
     knows, the base spelling wins, never the corpus's majority (a corpus's 427k lowercase
     `location` once outvoted the base's `Location`);
  3. fold matches between a corpus label and a base label are only PROPOSED, as comments,
     because the standing rule forbids merging on spelling alone: confirm by reading the
     surfaces in <name>.labels_review.md, then move the line into the map.

The map is closed before writing (no target is itself a key): it is applied once.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Dict, List, Tuple

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "tools/train"))
import build_label_maps as B  # noqa: E402
from label_review import inventory  # noqa: E402

REVIEW_TO_MAP = {"entities": "entities", "relations": "relations",
                 "event_types": "events", "roles": "events"}


def _clusters(mapping: Dict[str, str]) -> List[set]:
    by_winner: Dict[str, set] = {}
    for variant, winner in mapping.items():
        by_winner.setdefault(winner, {winner}).add(variant)
    return list(by_winner.values())


def _close(mapping: Dict[str, str]) -> Dict[str, str]:
    """Follow chains to their final spelling and drop identities."""
    out = {}
    for k in mapping:
        t, seen = mapping[k], {k}
        while t in mapping and t not in seen:
            seen.add(t)
            t = mapping[t]
        if t != k:
            out[k] = t
    return out


def build_labels(paths: List[str], model_info: Dict, review_rows: Dict) -> Tuple[Dict, Dict]:
    """Return (labels block, {category: {label: proposed base spelling}})."""
    base = model_info.get("label_map") or {}
    known = inventory(model_info) if model_info.get("has_label_inventory") else {}
    corpus_maps, _ = B.build(paths)
    block = {}
    for cat in B.CATEGORIES:
        bblock = base.get(cat) or {}
        mapping = dict(bblock.get("map") or {})
        base_spellings = set(mapping.values()) | known.get(cat, set())
        for members in _clusters(corpus_maps.get(cat) or {}):
            in_base = sorted(m for m in members if m in base_spellings)
            corpus_winner = next(w for w in members if w not in corpus_maps[cat])
            winner = in_base[0] if in_base else corpus_winner
            for m in members:
                if m != winner and m not in mapping:
                    mapping[m] = mapping.get(winner, winner)
        mapping = _close(mapping)
        if mapping or bblock:
            block[cat] = {"rollup": bool(bblock.get("rollup", False)),
                          "separator": bblock.get("separator", "."), "map": mapping}
    proposals: Dict[str, Dict[str, str]] = {}
    for rcat, rows in review_rows.items():
        cat = REVIEW_TO_MAP.get(rcat)
        for r in rows:
            if r["status"] == "fold_match" and r["label"] not in (block.get(cat) or {}).get("map", {}):
                proposals.setdefault(cat, {})[r["label"]] = r["target"]
    return block, proposals


def write_labels_file(path: Path, name: str, model: str, block: Dict, proposals: Dict) -> None:
    header = (f"# labels_file for fine-tuning {model} on {name} -- GENERATED by tools/derive.\n"
              "# = the base checkpoint's own label_map + the corpus's spelling clusters, base spelling\n"
              "# winning. Reference it from the config as `labels_file:` and keep NO inline `labels:`\n"
              "# block (an empty one silently overrides this file).\n")
    lines = [header, yaml.safe_dump({"labels": block}, allow_unicode=True, sort_keys=False,
                                    default_flow_style=False)]
    if proposals:
        lines.append("# PROPOSED -- corpus labels that fold onto a BASE spelling. NOT active: confirm each by\n"
                     f"# reading the surfaces it tags ({name}.labels_review.md), then move it into the map.\n")
        for cat, items in proposals.items():
            for label, target in items.items():
                lines.append(f"#   {cat}: {label!r}: {target!r}\n")
    path.write_text("".join(lines), encoding="utf-8")
